### ISSUE TITLE
Create more obvious way to use component just for events

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/aframe-keyboard-controls#3]
Some devs may want to use this component to generate named events, but not to move around. Currently this is achieved with `<a-entity keyboard-controls="enabled: false"></a-entity`, which is not a good syntax. `enabled: false` should disable _everything_, including events, and there should be separate documented options like `movementEnabled: true|false` or `eventsEnabled: true|false` to achieve this.

**Comment by armthethinker** [comment]
This would be useful. I've been using [KeyPress](https://dmauro.github.io/Keypress/) to handle my keyboard-tied events.
