### ISSUE TITLE
Polyfill Key redefinition error

### ISSUE THREAD

**Issue by ghost** [donmccurdy/aframe-keyboard-controls#4]
When running the current version, I get the error:
`
Uncaught TypeError: Cannot redefine property: key
`
<img width="627" alt="screen shot 2016-05-24 at 3 58 42 pm" src="https://cloud.githubusercontent.com/assets/14936355/15522619/a0fc8402-21c8-11e6-97f4-8eedcaad9fae.png">
It looks like the 'key' property of the KeyboardEvent class is being reset on line 692 of keyboard.polyfill.js.
This appears to be happening if the 'key' property already exists on the KeyboardEvent prototype, but it seems that it would make more sense to set the 'key' property if that property does NOT already exist.

I'm happy to make a pull request to apply the above logic.

**Comment by donmccurdy** [comment]
Archiving this project, in favor of movement-controls from 
https://github.com/donmccurdy/aframe-extras
